"use client";
import { useCallback, useEffect, useState } from "react";
import { Download, Search } from "lucide-react";
import { useDemoData } from "@/components/workspace-shell";
import { useDialogFocus } from "@/components/use-dialog-focus";
import type { AuditEvent, Transaction } from "@/lib/sample-data";
const displayTime=(value:string)=>{const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString()};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"EUR"});
export default function AuditPage(){const {snapshot,loading}=useDemoData();const [tab,setTab]=useState<"transactions"|"events">("transactions"),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[page,setPage]=useState(1),[selected,setSelected]=useState<Transaction|AuditEvent|null>(null);const size=10;const [pageData,setPageData]=useState<{items:(Transaction|AuditEvent)[];total:number}|null>(null),[pageError,setPageError]=useState("");
 const closeDetail=useCallback(()=>setSelected(null),[]);
 const detailRef=useDialogFocus<HTMLElement>(Boolean(selected),closeDetail);
 useEffect(()=>{let cancelled=false;const params=new URLSearchParams({kind:tab,search,status,page:String(page),size:String(size)});fetch(`/api/audit/page?${params}`,{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Could not load audit page.");if(!cancelled){setPageData(body);setPageError("");}}).catch(error=>{if(!cancelled)setPageError(error instanceof Error?error.message:"Could not load audit page.")});return()=>{cancelled=true};},[tab,search,status,page,snapshot]);
 const rows=pageData?.items??[];
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("transaction");if(id&&snapshot){const hit=snapshot.transactions.find(t=>t.id===id);if(hit)window.setTimeout(()=>setSelected(hit),0);}},[snapshot]);const shown=rows;const totalPages=Math.max(1,Math.ceil((pageData?.total??0)/size));function changeTab(next:"transactions"|"events"){setTab(next);setPage(1);setSelected(null)}
 const params=new URLSearchParams({format:"csv",kind:tab,search,status});return <><div className="page-heading"><div><div className="eyebrow">AUDIT & TRANSACTIONS</div><h1>Every decision has a trail</h1><p>Inspect actors, policy outcomes, evidence, and simulated payment status. Export all matching records.</p></div><div className="button-row"><a className="button-secondary" href={`/api/audit/export?${params.toString()}`}><Download size={17}/> CSV</a><a className="button-secondary" href={`/api/audit/export?${new URLSearchParams({...Object.fromEntries(params),format:"json"}).toString()}`}><Download size={17}/> JSON</a></div></div>
 {snapshot?.source==="sample"&&<div className="data-banner">Sample history only. Shared records require the demo database.</div>}{pageError&&<div className="data-banner" role="alert">{pageError}</div>}
 <section className="solid-panel"><div className="audit-toolbar"><div className="button-row" role="tablist"><button role="tab" aria-selected={tab==="transactions"} className={tab==="transactions"?"button-primary":"button-secondary"} onClick={()=>changeTab("transactions")}>Transactions</button><button role="tab" aria-selected={tab==="events"} className={tab==="events"?"button-primary":"button-secondary"} onClick={()=>changeTab("events")}>Events</button></div><label className="search-field"><Search size={17}/><span className="sr-only">Search history</span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search history"/></label><select aria-label="Filter by status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">All decisions</option>{["approved","escalated","released","blocked","pending"].map(v=><option key={v} value={v}>{v}</option>)}</select></div>
 {loading?<p>Loading audit trail…</p>:rows.length===0?<div className="empty-state"><h2>No matching records</h2><p>Change the search or filter, or run a demo scenario.</p></div>:<div className="table-scroll"><table className="data-table"><thead><tr>{(tab==="transactions"?["Time","Vendor / invoice","Amount","Decision","Actor"]:["Time","Actor","Action","Target","Decision"]).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{shown.map(row=>tab==="transactions"?<tr key={row.id} onClick={()=>setSelected(row)} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")setSelected(row)}}><td>{new Date((row as Transaction).createdAt).toLocaleString()}</td><td><strong>{(row as Transaction).vendorName}</strong><small>{(row as Transaction).invoiceId}</small></td><td>{money.format((row as Transaction).amount)}</td><td><span className={`status-pill ${(row as Transaction).status}`}>{(row as Transaction).status}</span></td><td>{(row as Transaction).decidedBy??(row as Transaction).agentName}</td></tr>:<tr key={row.id} onClick={()=>setSelected(row)} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")setSelected(row)}}><td>{displayTime((row as AuditEvent).createdAt)}</td><td>{(row as AuditEvent).actorName}</td><td>{(row as AuditEvent).action}</td><td>{(row as AuditEvent).target}</td><td><span className={`status-pill ${(row as AuditEvent).decision}`}>{(row as AuditEvent).decision}</span></td></tr>)}</tbody></table></div>}
 <div className="pagination"><span>{pageData?.total??0} matching records · page {page} of {totalPages}</span><div className="button-row"><button className="button-secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button-secondary" disabled={page===totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></section>
 {selected&&<div className="drawer-backdrop" onClick={closeDetail}><aside ref={detailRef} className="detail-drawer" role="dialog" aria-modal="true" aria-label="Record details" onClick={e=>e.stopPropagation()}><button className="button-secondary" onClick={closeDetail}>Close</button><div className="eyebrow">AUDIT DETAIL</div><h2>{selected.id}</h2><dl>{Object.entries(selected).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value??"—")}</dd></div>)}</dl></aside></div>}</>}
