"use client";
import { useCallback, useMemo, useState } from "react";
import { CheckCircle2, XCircle, AlertTriangle } from "lucide-react";
import { useDemoData } from "@/components/workspace-shell";
import { useDialogFocus } from "@/components/use-dialog-focus";
import type { Transaction } from "@/lib/sample-data";
const money = new Intl.NumberFormat("en-US",{style:"currency",currency:"EUR"});
export default function ApprovalsPage(){
 const {snapshot,loading,refresh}=useDemoData();
 const [filter,setFilter]=useState("pending"),[selected,setSelected]=useState<string|null>(null),[note,setNote]=useState(""),[confirm,setConfirm]=useState<"released"|"cancelled"|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const closeConfirm=useCallback(()=>setConfirm(null),[]);
 const confirmRef=useDialogFocus(Boolean(confirm),closeConfirm);
 const rows=useMemo(()=>snapshot?.transactions.filter(t=>filter==="all"||t.status===(filter==="pending"?"escalated":filter))??[],[snapshot,filter]);
 const item:Transaction|undefined=rows.find(t=>t.id===selected)??rows[0];
 async function decide(){if(!item||!confirm)return;setBusy(true);setMessage("");try{const response=await fetch("/api/payments/decision",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transactionId:item.id,decision:confirm,actorName:"Demo reviewer",note})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Decision could not be saved.");setMessage(`${confirm==="released"?"Human approved":"Human rejected"} · ${item.id}. Payment remains simulated.`);setSelected(null);setNote("");await refresh();window.dispatchEvent(new Event("agentpayops:updated"));}catch(error){setMessage(`${error instanceof Error?error.message:"Decision failed."} Refresh to see the current queue.`);await refresh();}finally{setBusy(false);setConfirm(null);}}
 return <><div className="page-heading"><div><div className="eyebrow">HUMAN REVIEW</div><h1>Decide with the evidence in view</h1><p>Escalated demo payments wait here. A human approval records a simulated completion; it does not transfer money.</p></div></div>
 {snapshot?.source==="sample"&&<div className="data-banner" role="status">Sample queue only. Connect the dedicated demo database to record decisions.</div>}
 {message&&<div className="data-banner" role="status">{message}</div>}
 <div className="button-row" role="group" aria-label="Queue filter">{["pending","released","blocked","all"].map(value=><button key={value} className={filter===value?"button-primary":"button-secondary"} onClick={()=>{setFilter(value);setSelected(null)}}>{value==="pending"?"Awaiting review":value[0].toUpperCase()+value.slice(1)}</button>)}</div>
 <div className="review-layout"><section className="solid-panel"><h2 className="panel-title">Queue <span className="muted-note">{rows.length}</span></h2>{loading?<p>Loading queue…</p>:rows.length===0?<p className="panel-copy">No items match this filter. Run an escalation or choose another view.</p>:<div className="review-list">{rows.map(row=><button key={row.id} className={`review-item ${item?.id===row.id?"selected":""}`} onClick={()=>setSelected(row.id)}><span><strong>{row.vendorName}</strong><small>{row.invoiceId} · {row.id}</small></span><span><strong>{money.format(row.amount)}</strong><small>{row.status}</small></span></button>)}</div>}</section>
 <section className="solid-panel">{item?<><div className="eyebrow">SELECTED PAYMENT</div><h2 className="panel-title">{item.vendorName}</h2><div className="detail-grid"><div><small>Amount</small><strong>{money.format(item.amount)}</strong></div><div><small>Status</small><strong className={`status-pill ${item.status}`}>{item.status}</strong></div><div><small>Invoice</small><strong>{item.invoiceId}</strong></div><div><small>Policy</small><strong>{item.policyDecision}</strong></div></div><h3>Why it needs review</h3><p className="panel-copy">{item.reason}</p><p className="muted-note">Recorded {new Date(item.createdAt).toLocaleString()} · {item.agentName}</p>{item.status==="escalated"&&<><label className="field-label" htmlFor="decision-note">Optional review note</label><textarea id="decision-note" maxLength={500} value={note} onChange={event=>setNote(event.target.value)} placeholder="Explain your decision for the audit trail"/><div className="button-row"><button className="button-primary" disabled={snapshot?.source!=="supabase"||busy} onClick={()=>setConfirm("released")}><CheckCircle2 size={17}/> Approve demo payment</button><button className="button-secondary" disabled={snapshot?.source!=="supabase"||busy} onClick={()=>setConfirm("cancelled")}><XCircle size={17}/> Reject</button></div></>}</>:<div className="empty-state"><AlertTriangle size={28}/><h2>No selected payment</h2><p>Choose a queue item to inspect its policy and evidence.</p></div>}</section></div>
 {confirm&&item&&<div className="dialog-backdrop" role="presentation"><div ref={confirmRef} className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{confirm==="released"?"Approve demo payment?":"Reject this payment?"}</h2><p>This records a human decision for {item.vendorName} ({money.format(item.amount)}) in the shared audit trail. Payment is simulated.</p><div className="button-row"><button className="button-secondary" onClick={closeConfirm}>Cancel</button><button className="button-primary" disabled={busy} onClick={()=>void decide()}>{busy?"Recording…":confirm==="released"?"Confirm approval":"Confirm rejection"}</button></div></div></div>}</>;
}
