"use client";
import { useEffect, useState } from "react";
import { RunStudio } from "@/components/run-studio";
import Link from "next/link";
import { ArrowRight, Brain, Database, FileSearch, ShieldAlert, SlidersHorizontal, UserCheck, WalletCards } from "lucide-react";
const layers=[
{number:"01",name:"Invoice intake",icon:FileSearch,summary:"Turn sample text or an image into fields and findings.",detail:"Unsupported documents return an explicit error. Extracted facts can be checked before evaluation."},
{number:"02",name:"Policy floor",icon:SlidersHorizontal,summary:"Apply category, vendor, amount, and duplicate rules.",detail:"Code makes the first decision. Rules can approve, block, or send a payment to human review."},
{number:"03",name:"Jev risk review",icon:ShieldAlert,summary:"Inspect context only after a policy approval.",detail:"Jev can turn an approval into an escalation. If unavailable, the UI shows rules-only evaluation."},
{number:"04",name:"Finance memo",icon:Brain,summary:"Explain the decision using Command Code when available.",detail:"The memo reports its source and latency. It never changes the policy decision."},
{number:"05",name:"Simulated payment",icon:WalletCards,summary:"Record a simulated payment outcome for an approved decision.",detail:"The guided run does not transfer funds. The separate vendor-risk endpoint can demonstrate a 402 challenge."},
{number:"06",name:"Human review",icon:UserCheck,summary:"A controller approves or rejects escalated demo payments.",detail:"One decision is recorded for each pending transaction. Conflicts ask visitors to refresh."},
{number:"07",name:"Audit ledger",icon:Database,summary:"Keep transactions, decisions, and actors in a shared history.",detail:"The public demo and presenter reset use a dedicated demo dataset."},
];
export default function ArchitecturePage(){const [activeStage,setActiveStage]=useState("");useEffect(()=>{const onStep=(event:Event)=>{const step=(event as CustomEvent<{name:string}>).detail;const stage:Record<string,string>={"Policy floor":"02","Jev review":"03","Finance memo":"04","Simulated payment":"05","Shared audit":"07"};setActiveStage(stage[step.name]??"")};window.addEventListener("agentpayops:run-step",onStep);return()=>window.removeEventListener("agentpayops:run-step",onStep)},[]);return <><div className="page-heading"><div><div className="eyebrow">HOW IT WORKS</div><h1>Seven visible steps from invoice to audit</h1><p>Follow how rules, AI review, human judgment, and the shared ledger each contribute to a payment decision.</p></div><Link className="button-primary" href="/runs?guide=1">Run the live walkthrough <ArrowRight size={17}/></Link></div><div className="architecture-list">{layers.map(({number,name,icon:Icon,summary,detail})=><details className={`glass-panel architecture-layer ${activeStage===number?"is-active":""}`} key={number}><summary><span className="layer-number">{number}</span><span className="layer-icon"><Icon size={22}/></span><span className="layer-main"><strong>{name}</strong><small>{summary}</small></span>{activeStage===number?<span className="layer-live">Live stage</span>:null}<span className="layer-plus">+</span></summary><p>{detail}</p></details>)}</div><div className="solid-panel" style={{marginTop:20}}><h2 className="panel-title">See each step with real inputs</h2><p className="panel-copy">The Agent Runs page calls the app APIs and shows actual outcomes. Its payment step is a simulation.</p><Link className="button-secondary" href="/runs">Open Agent Runs <ArrowRight size={17}/></Link></div><div style={{marginTop:20}}><RunStudio compact /></div></>}
