"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Play, RefreshCw } from "lucide-react";
import { useDemoData } from "@/components/workspace-shell";
import type { Decision, DemoScenario } from "@/lib/sample-data";
type Result={scenario:DemoScenario;payment:{status:Decision;paymentIssued:boolean;evaluation:{reason:string;checks:{label:string;passed:boolean}[];policyId:string|null}};memo:{headline:string;summary:string;source:string;evidence:string[]};policyDecision:Decision;jev:{riskLevel:string;suspicious:number;humanReview:number;latencyMs:number}|null;aiState:string;memoState:string;latencyMs:number;steps:{name:string;state:string}[]};
type RunRow={id:string;scenario_id:string;status:string;decision:Decision|null;payload:Result|null;created_at:string};
type RunReply={result?:Result;error?:string};
async function receiveRun(response:Response,onStep:(step:{name:string;state:string})=>void):Promise<RunReply>{
 if(!response.headers.get("content-type")?.includes("text/event-stream")){const body=await response.json() as RunReply;if(!response.ok)throw new Error(body.error||"Run failed.");return body;}
 if(!response.body)throw new Error("Live progress stream was unavailable. Retry the run.");
 const reader=response.body.getReader(),decoder=new TextDecoder();let pending="";let final:{status:number;body:RunReply}|null=null;
 while(true){const {value,done}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});const frames=pending.split(/\r?\n\r?\n/);pending=frames.pop()??"";for(const frame of frames){const line=frame.split(/\r?\n/).find(part=>part.startsWith("data: "));if(!line)continue;const event=JSON.parse(line.slice(6)) as {type:string;step?:{name:string;state:string};status?:number;body?:RunReply};if(event.type==="step"&&event.step)onStep(event.step);if(event.type==="result"&&event.body)final={status:event.status??500,body:event.body};}}
 if(!final)throw new Error("Run connection ended before a decision was recorded.");
 const completed=final as {status:number;body:RunReply};
 if(completed.status>=400)throw new Error(completed.body.error||"Run failed.");
 return completed.body;
}
const scenarios=[{id:"clean",title:"Clean purchase",expected:"approved",detail:"Allowlisted data purchase within policy"},{id:"rules",title:"Rules escalation",expected:"escalated",detail:"Cloud invoice above the finance threshold"},{id:"jev",title:"Jev fraud review",expected:"escalated if Jev flags risk",detail:"Changed wire details and urgent pressure"},{id:"duplicate",title:"Duplicate purchase",expected:"blocked after clean purchase",detail:"Repeat the same data purchase"},{id:"blocked-vendor",title:"Blocked vendor",expected:"blocked",detail:"Vendor on the payment blocklist"}];
export function RunStudio({compact=false}:{compact?:boolean}){const {refresh,invoiceDraft}=useDemoData();const [active,setActive]=useState<string|null>(null),[running,setRunning]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<Result|null>(null),[history,setHistory]=useState<RunRow[]>([]),[guide,setGuide]=useState(0),[liveSteps,setLiveSteps]=useState<{name:string;state:string}[]>([]);
 async function loadHistory(){try{const response=await fetch("/api/demo/runs",{cache:"no-store"});const body=await response.json();if(response.ok)setHistory(body.runs??[]);}catch{}}
 useEffect(()=>{const timer=setTimeout(()=>{void loadHistory();try{if(new URLSearchParams(window.location.search).has("guide")){sessionStorage.setItem("agentpayops:guide","0")}else setGuide(Math.min(3,Math.max(0,Number(sessionStorage.getItem("agentpayops:guide"))||0)))}catch{}},0);return()=>clearTimeout(timer)},[]);
 function advanceGuide(next:number){setGuide(next);try{sessionStorage.setItem("agentpayops:guide",String(next))}catch{}}
 async function run(id:string,custom?:Partial<DemoScenario>){setActive(id);setRunning(true);setLiveSteps([]);setError("");setResult(null);try{const response=await fetch("/api/demo/runs",{method:"POST",headers:{"content-type":"application/json",accept:"text/event-stream"},body:JSON.stringify(custom?{custom}:{scenarioId:id})});const body=await receiveRun(response,step=>{setLiveSteps(previous=>[...previous.filter(item=>item.name!==step.name),step]);window.dispatchEvent(new CustomEvent("agentpayops:run-step",{detail:step}));});if(!body.result)throw new Error(body.error||"Run returned no result.");setResult(body.result);await Promise.all([loadHistory(),refresh()]);window.dispatchEvent(new Event("agentpayops:updated"));if(id==="clean"&&body.result.payment.status==="approved")advanceGuide(1);else if(id==="rules"&&body.result.payment.status==="escalated")advanceGuide(2);else if(id==="jev")advanceGuide(3);}catch(cause){setError(cause instanceof Error?cause.message:"Run failed.");}finally{setRunning(false);}}
 let custom:Partial<DemoScenario>|null=null;try{const parsed=JSON.parse(invoiceDraft);if(parsed&&typeof parsed.vendorName==="string"&&typeof parsed.amount==="number")custom=parsed}catch{}
 return <div className="run-studio"><div className="glass-panel guide-next"><div><div className="eyebrow">GUIDED JOURNEY · STEP {Math.min(guide+1,4)} OF 4</div><h2 className="panel-title">{["Start with a clean purchase","Inspect a rules escalation","See a Jev fraud review","Review an escalation, then inspect audit"][guide]}</h2><p className="panel-copy">{guide<3?"Each run records its actual provider state and decision in the shared demo.":"Choose a pending payment and record a simulated human decision."}</p></div>{guide<3?<button className="button-primary" disabled={running} onClick={()=>void run(["clean","rules","jev"][guide])}><Play size={16}/> {running?"Running…":"Run this step"}</button>:<Link className="button-primary" href="/approvals">Open human review <ArrowRight size={16}/></Link>}</div><div className="glass-panel"><div className="panel-row"><div><div className="eyebrow">LIVE SCENARIOS</div><h2 className="panel-title">Choose a payment attempt</h2></div><span className="muted-note">Shared · simulated</span></div><div className="scenario-grid">{scenarios.map(s=><article className={`scenario-card ${active===s.id?"selected":""}`} key={s.id}><h3>{s.title}</h3><p>{s.detail}</p><small>Expected: {s.expected}</small><button className="button-secondary" disabled={running} onClick={()=>void run(s.id)}><Play size={16}/> {running&&active===s.id?"Running…":"Run scenario"}</button></article>)}</div>{custom&&<div className="custom-run"><span><strong>Edited invoice ready</strong><small>{custom.vendorName} · {custom.invoiceId} · €{custom.amount}</small></span><button className="button-primary" disabled={running} onClick={()=>void run("custom",custom??undefined)}>Evaluate edited invoice <ArrowRight size={16}/></button></div>}</div>
 {error&&<div className="data-banner" role="alert">{error} <button onClick={()=>active&&void run(active,active==="custom"?custom??undefined:undefined)}>Retry</button></div>}
 {running&&<div className="glass-panel run-progress" role="status"><RefreshCw className="animate-spin" size={20}/><div><strong>Evaluating on the server…</strong><p>Policy, eligible AI review, memo, and shared persistence. Provider calls may take a moment.</p><ol className="step-list">{liveSteps.map(step=><li key={step.name}><span>{step.name}</span><strong>{step.state}</strong></li>)}</ol></div></div>}
 {result&&<section className="solid-panel run-result" aria-live="polite"><div className="panel-row"><div><div className="eyebrow">RECORDED RUN</div><h2 className="panel-title">{result.scenario.name}</h2></div><span className={`status-pill ${result.payment.status}`}>{result.payment.status==="approved"?"Policy approved":result.payment.status}</span></div><p className="panel-copy">{result.payment.evaluation.reason}</p><div className="run-summary"><div><small>Expected</small><strong>{result.scenario.expectedDecision}</strong></div><div><small>Actual</small><strong>{result.payment.status}</strong></div><div><small>Jev</small><strong>{result.aiState}</strong></div><div><small>Command Code</small><strong>{result.memoState}</strong></div><div><small>Measured latency</small><strong>{result.latencyMs} ms</strong></div></div><ol className="step-list">{result.steps.map(step=><li key={step.name}><span>{step.name}</span><strong>{step.state}</strong></li>)}</ol><h3>Finance memo</h3><p><strong>{result.memo.headline}</strong></p><p className="panel-copy">{result.memo.summary}</p><small className="muted-note">Source: {result.memo.source}</small><details><summary>Policy checks and provider evidence</summary><ul>{result.payment.evaluation.checks.map(c=><li key={c.label}>{c.passed?"✓":"!"} {c.label}</li>)}</ul>{result.jev&&<p>Jev risk: {result.jev.riskLevel}; suspicious {result.jev.suspicious.toFixed(2)}; review {result.jev.humanReview.toFixed(2)}. Provider latency {result.jev.latencyMs} ms.</p>}</details><div className="button-row"><Link className="button-secondary" href="/approvals">Open human review <ArrowRight size={16}/></Link><Link className="button-secondary" href="/audit">Inspect audit trail <ArrowRight size={16}/></Link></div></section>}
 {!compact&&<section className="solid-panel run-history"><div className="panel-row"><h2 className="panel-title">Recent shared runs</h2><button className="button-secondary" onClick={()=>void loadHistory()}><RefreshCw size={16}/> Refresh</button></div>{history.length===0?<p className="panel-copy">No server-backed runs yet. Run a scenario to begin the shared record.</p>:<div className="recent-list">{history.map(row=><button className="recent-row history-row" key={row.id} onClick={()=>{if(row.payload)setResult(row.payload);setActive(row.scenario_id)}}><span><strong>{row.payload?.scenario.name??row.scenario_id}</strong><small>{new Date(row.created_at).toLocaleString()} · {row.id.slice(0,8)}</small></span><span className={`status-pill ${row.decision??"pending"}`}>{row.decision??row.status}</span></button>)}</div>}</section>}
 </div>}
