"use client";

import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, FileText, Fingerprint, Shield, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useDemoData } from "@/components/workspace-shell";

type Workflow = "intake" | "policy" | "approval";
const workflows: Record<Workflow, { label: string; eyebrow: string; title: string; description: string; route: string; action: string }> = {
  intake: { label: "Invoice intake", eyebrow: "01 / CAPTURE", title: "A document becomes a decision-ready record.", description: "Choose a sample or upload a supported file. Review extracted facts before the agent evaluates them.", route: "/invoices", action: "Open invoice intake" },
  policy: { label: "Policy review", eyebrow: "02 / EVALUATE", title: "Rules set the boundary before AI weighs in.", description: "Vendor, amount, category, and duplicate controls produce a traceable first decision. Optional risk review can escalate it.", route: "/runs", action: "Explore agent runs" },
  approval: { label: "Human approval", eyebrow: "03 / DECIDE", title: "Exceptions land with the right person.", description: "A reviewer sees the reason and evidence, approves or rejects, and leaves a recorded trail.", route: "/approvals", action: "View review queue" },
};
const stages = [
  ["01", "Intake", "Read the invoice and confirm the extracted facts."],
  ["02", "Evaluate", "Apply payment rules, with optional risk review only when allowed."],
  ["03", "Review", "Route exceptions to a human for an explicit decision."],
  ["04", "Record", "Keep outcome, actor, and provider state in the audit ledger."],
];
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });

function WorkflowStage({ selected }: { selected: Workflow }) {
  return <div className="product-stage">
    <div className="stage-chrome"><span className="stage-brand"><span className="stage-dot" /> AgentPayOps / workspace</span><span className="stage-mode">SAMPLE WORKFLOW</span></div>
    <div className="stage-content">
      <div className="stage-left"><div className="stage-small">PAYMENT CONTROL / {workflows[selected].eyebrow}</div><h3>{workflows[selected].title}</h3><p>{workflows[selected].description}</p><Link href={workflows[selected].route} className="stage-link">{workflows[selected].action} <ArrowUpRight size={17}/></Link></div>
      <div className="stage-document">
        <div className="document-top"><span className="document-icon"><FileText size={19}/></span><span>INVOICE / EXAMPLE</span><span className="document-options">•••</span></div>
        <div className="document-rule" /><div className="document-vendor">Northstar Supply</div><div className="document-sub">INV-2026-041 · Operations</div>
        <div className="document-facts"><span>Invoice total</span><strong>€2,480.00</strong></div><div className="document-facts"><span>Payment status</span><strong>{selected === "approval" ? "Awaiting review" : selected === "policy" ? "Policy evaluation" : "Ready for review"}</strong></div>
        <div className="document-rule" /><div className="document-foot"><span className="document-check"><Check size={14}/></span><span>{selected === "intake" ? "Fields extracted for verification" : selected === "policy" ? "Policy evidence attached" : "Human decision required"}</span></div>
      </div>
    </div><div className="stage-bottom"><span>Invoice intake</span><ArrowRight size={14}/><span>Policy floor</span><ArrowRight size={14}/><span>Human review</span><ArrowRight size={14}/><span>Audit record</span></div>
  </div>;
}

export default function HomePage() {
  const { snapshot, loading, error } = useDemoData();
  const [selected, setSelected] = useState<Workflow>("intake");
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { if (window.location.hash === "#approval-queue") window.location.replace("/approvals"); }, []);
  const source = snapshot?.source === "sample" ? "Sample dataset" : "Live demo";
  const overview = snapshot?.overview;
  const metrics = [
    { label: "Spend reviewed", value: money.format(overview?.spendReviewed ?? 0), note: "Across recorded attempts", href: "/dashboard", visual: "bars" },
    { label: "Awaiting review", value: String(overview?.pendingReview ?? 0).padStart(2, "0"), note: "Needs a human decision", href: "/approvals", visual: "ticks" },
    { label: "Human decisions", value: String(overview?.humanDecisions ?? 0).padStart(2, "0"), note: "Recorded in the ledger", href: "/audit", visual: "line" },
  ];
  const latest = snapshot?.transactions?.[0];
  return <div className="marketing-frame"><main id="main-content" className="marketing-canvas">
    <div className="marketing-hero" id="top">
      <svg className="hero-geometry" viewBox="0 0 1440 840" preserveAspectRatio="xMidYMin slice" aria-hidden="true"><path d="M0 0L690 710M1440 0L690 710M0 560L1440 560M170 0V840M430 0V840M850 0V840M1200 0V840"/><circle cx="720" cy="520" r="390"/><circle cx="720" cy="520" r="285"/><circle cx="720" cy="520" r="180"/><path d="M0 310H1440M0 0L1440 840M1440 0L0 840"/></svg>
      <header className="marketing-header"><Link className="marketing-logo" href="/" aria-label="AgentPayOps home"><span className="logo-symbol"><Shield size={19}/></span><span>AgentPayOps</span></Link><nav className="marketing-nav" aria-label="Homepage"><a href="#workflow">Workflow</a><a href="#controls">Controls</a><a href="#architecture">Architecture</a><Link href="/dashboard">Workspace <ArrowUpRight size={13}/></Link></nav><Link className="header-action" href="/dashboard">Open workspace <ArrowUpRight size={15}/></Link><button className="marketing-menu-button" type="button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>Menu <span>{menuOpen ? "×" : "☰"}</span></button></header>
      {menuOpen && <nav className="marketing-mobile-nav" aria-label="Mobile homepage"><a href="#workflow" onClick={() => setMenuOpen(false)}>Workflow</a><a href="#controls" onClick={() => setMenuOpen(false)}>Controls</a><a href="#architecture" onClick={() => setMenuOpen(false)}>Architecture</a><Link href="/dashboard">Open workspace</Link></nav>}
      <div className="hero-copy"><span className="hero-label">FINANCE OPERATIONS / SHARED DEMO</span><h1>Agent payments.<br/>Clear decisions.</h1><p>Give autonomous payments a clear path from invoice to policy, optional AI review, human approval, and a recorded outcome.</p><div className="hero-actions"><Link className="hero-primary" href="/runs?guide=1">Start live demo <ArrowUpRight size={17}/></Link><a className="hero-secondary" href="#workflow">See how it works <ArrowDown size={16}/></a></div><span className="hero-disclaimer">Shared demo <span>·</span> Payments are simulated</span></div>
      <div className="hero-metrics" aria-label="Demo activity summaries">{metrics.map((metric, index) => <Link className="hero-metric" href={metric.href} key={metric.label}><div className="metric-head"><span>{metric.label}</span><ArrowUpRight size={15}/></div><strong>{loading ? "—" : error ? "Unavailable" : metric.value}</strong><span className="hero-metric-note">{error ? "Ledger disconnected" : loading ? "Loading ledger" : `${source} · ${metric.note}`}</span><div className={`metric-visual ${metric.visual}`} aria-hidden="true">{Array.from({ length: 18 }, (_, i) => <i key={i} style={{ height: `${15 + ((i * 17 + index * 13) % 55)}%` }} />)}</div></Link>)}</div>
    </div>
    <section className="marketing-section workflow-section" id="workflow"><div className="center-intro"><span className="section-kicker">WHAT HAPPENS NEXT</span><h2>From invoice to<br/>recorded decision.</h2><p>One connected flow for the facts, controls, people, and evidence behind every demo payment.</p></div><div className="workflow-tabs" role="group" aria-label="Explore the workflow">{(Object.keys(workflows) as Workflow[]).map(id => <button key={id} type="button" aria-pressed={selected === id} onClick={() => setSelected(id)}>{workflows[id].label}</button>)}</div><WorkflowStage selected={selected}/></section>
    <section className="marketing-section editorial-section" id="controls"><div className="editorial-heading"><div><span className="section-kicker">ONE CONNECTED RECORD</span><h2>When agents act, finance stays in the loop.</h2></div><p>AgentPayOps links invoice facts, policy decisions, optional risk context, human review, and the audit trail. Each step has a reason you can inspect.</p></div><div className="proof-strip"><div><strong>01</strong><span>Invoice facts you can verify</span></div><div><strong>02</strong><span>Explicit policy outcomes</span></div><div><strong>03</strong><span>Recorded human decisions</span></div></div></section>
    <section className="process-section" id="architecture"><div className="process-top"><div><span className="section-kicker light">THE DECISION PATH</span><h2>From scattered inputs.<br/>To clear decisions.</h2></div><p>Each stage adds context, and the audit record keeps the final outcome traceable. Follow the live run to see the actual provider state.</p></div><div className="process-body"><div className="process-art" aria-hidden="true"><div className="process-axis"/><div className="process-rings"/>{Array.from({length:28},(_,i)=><i key={i} style={{height:`${20+Math.sin(i/27*Math.PI)*58}%`}}/>)}</div><ol className="process-steps">{stages.map(([number,title,description])=><li key={number}><span>{number} / {title.toUpperCase()}</span><strong>{title}</strong><p>{description}</p></li>)}<li className="process-link"><Link href="/architecture">Explore the architecture <ArrowUpRight size={17}/></Link></li></ol></div></section>
    <section className="marketing-section principles-section"><div className="section-kicker">CONTROL BY DESIGN</div><h2>Better payments start<br/>with better decisions.</h2><div className="principle-grid"><article><span className="principle-art"><Shield size={56} strokeWidth={1}/></span><h3>Rules set the boundary.</h3><p>Vendor, amount, category, and duplicate checks create a clear first decision.</p></article><article><span className="principle-art"><Fingerprint size={56} strokeWidth={1}/></span><h3>People decide exceptions.</h3><p>Escalations put the reason and evidence in front of a human reviewer.</p></article><article><span className="principle-art"><Sparkles size={56} strokeWidth={1}/></span><h3>Every action leaves evidence.</h3><p>Find decisions, actors, and provider outcomes in one shared audit record.</p></article></div></section>
    <section className="evidence-section"><div className="evidence-heading"><div><span className="section-kicker">RECORDED ACTIVITY</span><h2>A decision you can trace.</h2></div><p>The demo ledger shows what actually happened. Open any transaction to inspect its evidence and recorded outcome.</p></div><div className="evidence-record"><div className="record-icon"><FileText size={31}/></div><div><span className="record-label">{loading ? "LOADING RECORD" : error ? "LEDGER UNAVAILABLE" : source.toUpperCase()}</span><h3>{latest?.vendorName ?? (loading ? "Loading a recorded case" : "No transactions yet")}</h3><p>{latest ? `${latest.invoiceId} · ${money.format(latest.amount)} · ${latest.status}` : error ? "Reconnect the ledger from the workspace." : "Start a guided run to create a decision."}</p></div><Link href={latest ? `/audit?transaction=${encodeURIComponent(latest.id)}` : "/runs?guide=1"} className="record-action">{latest ? "Inspect decision" : "Start a run"} <ArrowUpRight size={17}/></Link></div></section>
    <section className="resource-section marketing-section"><div><span className="section-kicker">EXPLORE THE PROJECT</span><h2>See the system<br/>from every angle.</h2></div><div className="resource-links"><Link href="/architecture"><span>01 / ARCHITECTURE</span><strong>How a payment moves from intake to audit</strong><ArrowUpRight size={21}/></Link><Link href="/runs?guide=1"><span>02 / LIVE DEMO</span><strong>Run a guided scenario through the controls</strong><ArrowUpRight size={21}/></Link><a href="https://github.com/anilandcode/AgentPayOps" target="_blank" rel="noopener noreferrer"><span>03 / SOURCE CODE</span><strong>Explore the implementation on GitHub</strong><ArrowUpRight size={21}/></a></div></section>
    <footer className="marketing-footer"><div className="footer-cta"><div className="footer-visual" aria-hidden="true"><div className="footer-visual-top">AGENTPAYOPS / AUDIT RECORD <span>↗</span></div><div className="footer-visual-amount">€2,480.00</div><div className="footer-visual-line"><span>Decision</span><strong>Review required</strong></div><div className="footer-visual-line"><span>Evidence</span><strong>Policy + invoice</strong></div><div className="footer-visual-line"><span>Provider</span><strong>Simulated</strong></div></div><div><span className="section-kicker light">START WITH A REAL WORKFLOW</span><h2>See a payment<br/>decision happen.</h2><Link href="/runs?guide=1" className="hero-primary">Start live demo <ArrowUpRight size={17}/></Link></div></div><div className="footer-bottom"><div><Link className="marketing-logo" href="/"><span className="logo-symbol"><Shield size={18}/></span> AgentPayOps</Link><p>Finance controls for autonomous payments.<br/>Shared demo · Payments are simulated.</p></div><div><strong>PRODUCT</strong><Link href="/dashboard">Workspace</Link><Link href="/invoices">Invoice intake</Link><Link href="/approvals">Human review</Link></div><div><strong>EXPLORE</strong><Link href="/architecture">Architecture</Link><Link href="/audit">Audit trail</Link><a href="https://github.com/anilandcode/AgentPayOps" target="_blank" rel="noopener noreferrer">Source code</a></div></div><div className="footer-copyright">© 2026 AgentPayOps <span>Simulated payment workflow</span></div></footer>
  </main></div>;
}
